-- SQL File for dropping all data in the tables; the tables themselves remain on the db
--
-- Grid for Digital Security (G4DS)
-- Michael Pilgermann
-- mpilgerm@glam.ac.uk

DELETE FROM ROUTINGTABLE;
DELETE FROM SERVICES_AUTHORITIES;
DELETE FROM SERVICES_MEMBERS;
DELETE FROM SERVICES_COMMUNITIES;
DELETE FROM SERVICES;
DELETE FROM COMMUNITIES_ALGORITHMS;
DELETE FROM PERSONALCREDENTIALS;
DELETE FROM COMMUNITIES_PROTOCOLS;
DELETE FROM ENDPOINTS;
DELETE FROM PROTOCOLS;
DELETE FROM CREDENTIALS;
DELETE FROM ALGORITHMS;
DELETE FROM GATEWAYS;
DELETE FROM COMMUNITIES_MEMBERS;
DELETE FROM COMMUNITIES_AUTHORITIES;
DELETE FROM MEMBERS;
DELETE FROM COMMUNITIES;
